# Generated by Django 5.0 on 2025-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage='django.core.files.storage.FileSystemStorage', upload_to='avatars/'),
        ),
    ]
