# Generated by Django 5.0 on 2025-11-28 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_pay_on_delivery', models.BooleanField(default=True)),
                ('allow_online_payment', models.BooleanField(default=True)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('terms_and_conditions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='site/')),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Information',
            },
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Leave empty for general slider', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brandmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
