# Generated by Django 5.0 on 2025-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfomodel',
            name='logo',
            field=models.ImageField(storage='django.core.files.storage.FileSystemStorage', upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(storage='django.core.files.storage.FileSystemStorage', upload_to='sliders/'),
        ),
    ]
