# Generated by Django 5.0 on 2025-12-08 17:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_alter_siteinfomodel_logo_alter_slidermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfomodel',
            name='logo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='sliders/'),
        ),
    ]
