# Generated by Django 5.0 on 2025-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_alter_siteinfomodel_logo_alter_slidermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
