# Generated by Django 5.0 on 2025-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='featured_image',
            field=models.ImageField(storage='django.core.files.storage.FileSystemStorage', upload_to='blog/'),
        ),
    ]
