# Generated by Django 5.0 on 2025-12-08 17:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpostmodel_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='featured_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='blog/'),
        ),
    ]
