# Generated by Django 5.0 on 2026-01-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpostmodel_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
