# Generated by Django 5.0 on 2025-12-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
    ]
