# Generated by Django 5.0 on 2026-02-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermodel_is_paid_ordermodel_logistic_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='expected_delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
