# Generated by Django 5.0 on 2025-12-08 17:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brandmodel_logo_alter_categorymodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='reviews/'),
        ),
    ]
