# Generated by Django 5.0 on 2025-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brandmodel_logo_alter_categorymodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
