# Generated by Django 5.0 on 2025-12-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['name'], name='products_pr_name_d562ce_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['brand', 'category'], name='products_pr_brand_i_9927e8_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['-created_at'], name='products_pr_created_628a63_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['-view_count'], name='products_pr_view_co_892671_idx'),
        ),
    ]
