# Generated by Django 6.0.2 on 2026-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmodel_products_pr_name_d562ce_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
